---

    - name: Install postgresql 
      package:
        name: "{{ postgresql_packages }}"
        state: present
      notify: 
        - Start PostgreSQL

    - name: Add PostgreSQL dependencies on Debian
      when: ansible_os_family == "Debian"
      package:
        name:
          - python3-psycopg2
        state: present
      notify: 
        - Start PostgreSQL

    # - name: Add PostgreSQL dependencies on Centos
    #   when: ansible_os_family == "Centos"
    #   package:
    #     name:
    #       - postgresql-server
    #       - libpq-devel 
    #     state: present
    #   notify:
    #     - Start PostgreSQL



    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user: 
        name: "{{ db_user }}"
        password: " {{ db_password }} "  
        encrypted: yes

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        encoding: UTF8
        template: template0

    - name: Create PostgreSQL extensions
      become_user: postgres
      vars: 
        postgresql_extensions:
          - "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
          - "CREATE EXTENSION IF NOT EXISTS unaccent;"
      loop: "{{ postgresql_extensions }}"
      postgresql_query:
        db: "{{ db_name }}"  
        query: "{{ item }}"
        state: present

      
      




    
    






    
