---
- name: Control Node
  hosts: localhost
  tasks:
    - name: Generate SSH Key
      community.crypto.openssh_keypair:
        path: "{{ ansible_ssh_private_key_file }}"
        type: ed25519
        size: 2048
        state: present
        force: false

- name: Initial Playbook
  hosts: all
  roles:
    - init
