---
- name: Install Peertube
  hosts: peertube
  roles:
    - dependencies
    - user
    - database
    - prepare_directories
    # - peertube config
    # - webserver
    # - linux_tcp_tuning
    # - systemd
