---
- name: Control Node
  hosts: localhost
  tasks:
    - name: Generate SSH Key
      community.crypto.openssh_keypair:
        path: "/home/{{ansible_user}}/.ssh/id_ed25519"
        type: ed25519
        size: 2048
        state: present
        force: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
- name: Initial Playbook
  hosts: all
  roles:
    - init
