---
- name: Create peertube user
  ansible.builtin.user:
    name: "{{ peertube_user }}"
    shell: /bin/bash
    home: "{{ peertube_path }}"
    password: "{{ peertube_password }}"
    state: present

- name: Apply rights on home folder
  ansible.builtin.file:
    path: "/var/www/peertube/"
    state: directory
    owner: peertube
    group: peertube
    mode: '0755'
    recurse: true
