---
- name: Create peertube user
  ansible.builtin.user:
    name: "{{ peertube_user }}"
    shell: /bin/bash
    home: "{{ peertube_path }}"
    password: "{{ peertube_password }}"
    state: present
