---
- name: Add PostgreSQL dependencies on Debian
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name:
      - python3-psycopg2
    state: present
  notify:
    - Start PostgreSQL

- name: Create a PostgreSQL user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: true

- name: Create a PostgreSQL database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF-8
    template: template0

- name: Create PostgreSQL extensions
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: "{{ item }}"
    db: "{{ db_name }}"
  with_items:
    - pg_trgm
    - unaccent
  notify:
    - Restart PostgreSQL
