---
- name: Start PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
