---
- name: Copy default.yaml to config directory as the peertube user
  ansible.builtin.copy:
    src: "{{ peertube_path }}/peertube-latest/config/default.yaml"
    dest: "{{ peertube_path }}/config/default.yaml"
    remote_src: true
    owner: peertube
    group: peertube
    mode: '0644'

# TODO: import ownn file
- name: Copy production.yaml.example to production.yaml as the peertube user
  ansible.builtin.template:
    src: "files/config.yaml.j2"
    dest: "{{ peertube_path }}/config/production.yaml"
    owner: peertube
    group: peertube
    mode: '0644'
