---
- name: Install PeerTube dependencies
  ansible.builtin.apt:
    name: "{{ dependencies_list }}"
    state: present
  notify: Start redis

- name: Check if Yarn is installed
  ansible.builtin.command: yarn --version
  register: yarn_version
  failed_when: false
  changed_when: false

- name: Install Yarn if it is not installed
  ansible.builtin.shell: npm install --global yarn
  when: yarn_version.rc != 0

- name: Update npm to the latest version
  ansible.builtin.shell: npm install -g npm
  register: npm_update
  changed_when: "'updated' in npm_update.stdout"
